name: Build and Submit for Staging
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build for Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: npm install
      - name: Install EAS CLI
        run: npm install -g eas-cli
      - name: EAS Build
        run: npx eas build --profile preview4 --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - name: EAS Submit
        run: npx eas submit --platform android --profile staging --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
